apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: urgent-hornet-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:ca0a23e7f9ae308241b40741c90134df963b4cee@sha256:74d823947b47437ec1b4d1c8d5fd69fca3fc4f4b50524c4ebe28edd74bf74c74
        name: container-image  
